// Generated by LiveScript 1.5.0
(function(){
  var client_pkg, client_pkg_list, i$, ref$, len$, ft, j$, len1$, pkg, cfg;
  client_pkg = ['jquery', 'snapsvg', 'semantic-ui'];
  client_pkg_list = [];
  for (i$ = 0, len$ = (ref$ = ['js', 'css']).length; i$ < len$; ++i$) {
    ft = ref$[i$];
    for (j$ = 0, len1$ = client_pkg.length; j$ < len1$; ++j$) {
      pkg = client_pkg[j$];
      client_pkg_list.push({
        expand: true,
        cwd: 'node_modules/' + pkg + '/dist',
        src: '*',
        dest: '../pkg/' + pkg + '/'
      });
    }
  }
  client_pkg = {
    files: client_pkg_list
  };
  cfg = {
    copy: {
      pkg: client_pkg
    },
    pug: {
      src: {
        expand: true,
        src: ['*.pug'],
        dest: '../',
        ext: '.html'
      },
      options: {
        pretty: true
      }
    },
    stylus: {
      src: {
        expand: true,
        src: ['*.styl'],
        dest: '../css/',
        ext: '.css'
      }
    },
    livescript: {
      src: {
        expand: true,
        src: ['*.ls', '!Gruntfile.ls'],
        dest: '../js/',
        ext: '.js'
      },
      options: {
        bare: true
      }
    }
  };
  module.exports = function(grunt){
    grunt.initConfig(cfg);
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-pug');
    grunt.loadNpmTasks('grunt-contrib-stylus');
    grunt.loadNpmTasks('grunt-livescript');
    return grunt.registerTask('default', ['pug', 'stylus', 'livescript', 'copy']);
  };
}).call(this);
